In [2]:
import numpy as np
import pandas as pd

**CREATEING A DATA FRAME**

In [3]:
data = {
'Name': ['John', 'Anna', 'Peter', 'Linda'],
'Age': [28, 34, 29, 42],
'City': ['New York', 'Paris', 'Berlin', 'London'],
'Salary': [65000, 70000, 62000, 85000]
}

In [4]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [6]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [7]:
#create datafreme using list colum set manually 
data_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
]
column = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=column)

In [8]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection  and indexing of columns**

In [9]:
 df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#select name columns
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [11]:
#select name city
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [12]:
# select 2 column name and city 
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**CREARING A NEW COLUMN**

In [13]:
df2["Degination"]=["Docter","Engineering","doctro","worker"]

In [14]:
df2

    Name  Age      City  Salary   Degination
0   John   28  New York   65000       Docter
1   Anna   34     Paris   70000  Engineering
2  Peter   29    Berlin   62000       doctro
3  Linda   42    London   85000       worker

Removing column

In [18]:
#delete a coloumn form data Frame
df2.drop("Degination", axis = 1,inplace = True)

In [45]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [46]:
#delete multiple column delete 
df2.drop(["City","Salary"], axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

Selection a rows

In [47]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [49]:
#select multiple rows 
df2.loc[[0,1]] #loc menas location

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

Selectin Subsets of Rows and Column

In [50]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [51]:
df2.loc[[0,1]][["Name","Age"]]

   Name  Age
0  John   28
1  Anna   34

**Condition Selection**

In [52]:
# I want to see those people whose age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [56]:
# I want to see those people  whose age is above 30 and city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000